name: ASV

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  pull_request:    

jobs:
  build:
    name: Build and run benchmarks
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'scipp/scipp'
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version
      - uses: actions/checkout@v3
        with:
          path: 'scipp-benchmarks'

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt

      - uses: hendrikmuhs/ccache-action@v1.2.2

      - run: tox -e lib
      - run: tox -e asv

      - name: Deploy benchmark results
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: scipp-benchmarks
          single-commit: true
