name: ASV

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  pull_request:    

jobs:
  build:
    name: Build and run benchmarks
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0} # required for conda env
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'scipp/scipp'
          submodules: true
          fetch-depth: 0  # history required so cmake can determine version

      - name: Setup conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: 2.5.0-1
          environment-file: .buildconfig/ci-linux.yml
          cache-environment: true
          create-args: python=3.11

      - uses: actions/checkout@v4
        with:
          path: 'scipp-benchmarks'

      - uses: hendrikmuhs/ccache-action@v1.2.20

      - run: cmake --preset ci-linux
      - run: cmake --build --preset build
      - run: ctest --preset test
      - run: python -m pip install -r requirements/asv.txt
      - name: Run ASV benchmarks
        env:
          PYTHONPATH: ${{ github.workspace }}/install
          LD_LIBRARY_PATH: ${{ github.workspace }}/install/lib
        run: |
          asv machine --machine cloud-container --os "Ubuntu" --arch 'x86_64' --cpu "2 Core CPU" --num_cpu 2 --ram '7GB'
          asv update
          asv run -v -m cloud-container -e --environment existing:python --set-commit-hash HEAD
          asv publish

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: scipp-benchmarks
          file_pattern: results/*

      - name: Deploy benchmark results
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh_pages
          folder: scipp-benchmarks/docs
          single-commit: true
