name: Benchmark scipp

on: 
  schedule:
    - cron: '0 * * * *'
  push:
  

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      CCACHE_BASEDIR: "${{ github.workspace }}"
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_MAXSIZE: 400M

    steps:
      - uses: actions/checkout@v2

      - name: Check if commit already benched
        shell: bash -l {0}
        run: |
          export SCIPP_COMMIT_HASH="echo $(command git ls-remote https://github.com/scipp/scipp HEAD | head -n1 | sed -e 's/\s.*$//')"
          grep -Fxv "$SCIPP_COMMIT_HASH" scipp_commit_hash

      - name: Clone Scipp
        shell: bash -l {0}
        run: git clone https://github.com/scipp/scipp repo

      - name: Setup Mambaforge and Scipp dev env
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: repo/scipp-developer.yml
          activate-environment: scipp-developer
          auto-activate-base: false
      
      - name: Install and Setup ccache
        shell: bash -l {0}
        run: |
          sudo apt-get update -y && sudo apt-get install -y ccache
          # Make gcc/gxx symlinks first in path
          sudo /usr/sbin/update-ccache-symlinks
          echo "/usr/lib/ccache" >> $GITHUB_PATH
          # Prep Ccache
          echo "::set-output name=key::benchmark-$RUNNER_OS"
          echo "::set-output name=timestamp::$(date +%Y%m%d-%H%M%S)"
          ccache -p
          ccache -z
      
      - name: "Restore ccache"
        uses: actions/cache@v1.1.0
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: .ccache
          key:  ${{ runner.os }}-ccache-${{ env.CACHE_NUMBER }}

      - name: Install asv
        shell: bash -l {0}
        run: pip install asv

      - name: Configure asv
        shell: bash -l {0}
        run: asv machine --machine cloud-container --os "Ubuntu latest" --arch 'x86_64' --cpu "2 Core CPU" --num_cpu 2 --ram '7GB'

      - name: Run asv benchmarks
        shell: bash -l {0}
        run: |
          # Use mamba for env creation
          export CONDA_EXE=$(which mamba)
          asv run -v -m cloud-container -e
        
      - name: "Check ccache performance"
        shell: bash -l {0}
        run: ccache -s
        if: always()

      - name: Commit changes and new results to github pages
        shell: bash -l {0}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add results/\*
          git commit -m "[Bot] Update results"

      - name: Create the Scipp repo commit hash file
        shell: bash -l {0}
        run: |
          $SCIPP_COMMIT_HASH > scipp_commit_hash

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Publish asv results locally
        shell: bash -l {0}
        run: asv publish

# Remove all but the website html folder, copy contents of html one higher, remove html,
# stash to revert main back to before cleaning, then git checkout gh_pages, before
# popping the stash and applying all changes for this branch.
      - name: Prep website for gh_pages branch
        shell: bash -l {0}
        run: |
          shopt -s extglob
          rm -v !("html") -rf -v
          cp -a ./html/* . -v
          rm -rf html -v
          rm -rf .github -v
          rm -rf .idea -v
          git add *
          git stash
          git fetch
          git checkout gh_pages
          git checkout stash -- .

      - name: Commit changes and new results to github pages
        shell: bash -l {0}
        run: |
          git add *
          git commit -m "[Bot] Publish to Github Pages"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh_pages
